In [20]:
%pip install beautifulsoup4
import pandas as pd
import numpy as np
import random 
from bs4 import BeautifulSoup
import requests

Requirement already satisfied: beautifulsoup4 in /home/jupyterlab/conda/envs/python/lib/python3.6/site-packages (4.8.0)
Requirement already satisfied: soupsieve>=1.2 in /home/jupyterlab/conda/envs/python/lib/python3.6/site-packages (from beautifulsoup4) (1.9.3)
Note: you may need to restart the kernel to use updated packages.

In [4]:
!conda update -n base -c defaults conda --yes

Solving environment: done

## Package Plan ##

  environment location: /home/jupyterlab/conda

  added / updated specs:
    - conda


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-package-handling-1.3.11|           py37_0         260 KB
    certifi-2019.6.16          |           py37_1         156 KB
    libxml2-2.9.9              |       hea5a465_1         2.0 MB
    ca-certificates-2019.5.15  |                1         134 KB
    chardet-3.0.4              |        py37_1003         173 KB
    python-3.7.4               |       h265db76_1        36.5 MB
    pysocks-1.7.0              |           py37_0          29 KB
    python-libarchive-c-2.8    |          py37_13          23 KB
    pip-19.2.2                 |           py37_0         1.9 MB
    conda-4.7.11               |           py37_0         3.0 MB
    ncurses-6.1                |       he6710b0_1         958 KB
    pycparser-2.19             |           py37_0         172 KB
    pyopenssl-19.0.0           |           py37_0          82 KB
    idna-2.8                   |           py37_0         101 KB
    zlib-1.2.11                |       h7b6447c_3         120 KB
    libedit-3.1.20181209       |       hc058e9b_0         188 KB
    sqlite-3.29.0              |       h7b6447c_0         1.9 MB
    zstd-1.3.7                 |       h0b5b093_0         887 KB
    openssl-1.1.1c             |       h7b6447c_1         3.8 MB
    cryptography-2.7           |   py37h1ba5d50_0         608 KB
    urllib3-1.24.2             |           py37_0         153 KB
    lz4-c-1.8.1.2              |       h14c3975_0         158 KB
    setuptools-41.0.1          |           py37_0         648 KB
    six-1.12.0                 |           py37_0          22 KB
    wheel-0.33.4               |           py37_0          39 KB
    cffi-1.12.3                |   py37h2e261b9_0         222 KB
    tqdm-4.32.1                |             py_0          48 KB
    libarchive-3.3.3           |       h5d8350f_5         1.5 MB
    bzip2-1.0.8                |       h7b6447c_0         105 KB
    requests-2.22.0            |           py37_0          89 KB
    ------------------------------------------------------------
                                           Total:        55.8 MB

The following NEW packages will be INSTALLED:

    _libgcc_mutex:          0.1-main
    conda-package-handling: 1.3.11-py37_0
    libarchive:             3.3.3-h5d8350f_5
    lz4-c:                  1.8.1.2-h14c3975_0
    python-libarchive-c:    2.8-py37_13
    zstd:                   1.3.7-h0b5b093_0

The following packages will be UPDATED:

    bzip2:                  1.0.6-h14c3975_5        --> 1.0.8-h7b6447c_0
    ca-certificates:        2018.03.07-0            --> 2019.5.15-1
    certifi:                2018.8.24-py37_1        --> 2019.6.16-py37_1
    cffi:                   1.11.5-py37he75722e_1   --> 1.12.3-py37h2e261b9_0
    chardet:                3.0.4-py37_1            --> 3.0.4-py37_1003
    conda:                  4.5.11-py37_0           --> 4.7.11-py37_0
    cryptography:           2.3.1-py37hc365091_0    --> 2.7-py37h1ba5d50_0
    idna:                   2.7-py37_0              --> 2.8-py37_0
    libedit:                3.1.20170329-h6b74fdf_2 --> 3.1.20181209-hc058e9b_0
    libgcc-ng:              8.2.0-hdf63c60_1        --> 9.1.0-hdf63c60_0
    libxml2:                2.9.8-h26e45fe_1        --> 2.9.9-hea5a465_1
    ncurses:                6.1-hf484d3e_0          --> 6.1-he6710b0_1
    openssl:                1.0.2p-h14c3975_0       --> 1.1.1c-h7b6447c_1
    pip:                    10.0.1-py37_0           --> 19.2.2-py37_0
    pycparser:              2.18-py37_1             --> 2.19-py37_0
    pyopenssl:              18.0.0-py37_0           --> 19.0.0-py37_0
    pysocks:                1.6.8-py37_0            --> 1.7.0-py37_0
    python:                 3.7.0-hc3d631a_0        --> 3.7.4-h265db76_1
    requests:               2.19.1-py37_0           --> 2.22.0-py37_0
    setuptools:             40.2.0-py37_0           --> 41.0.1-py37_0
    six:                    1.11.0-py37_1           --> 1.12.0-py37_0
    sqlite:                 3.24.0-h84994c4_0       --> 3.29.0-h7b6447c_0
    tqdm:                   4.26.0-py37h28b3542_0   --> 4.32.1-py_0
    urllib3:                1.23-py37_0             --> 1.24.2-py37_0
    wheel:                  0.31.1-py37_0           --> 0.33.4-py37_0
    zlib:                   1.2.11-ha838bed_2       --> 1.2.11-h7b6447c_3


Downloading and Extracting Packages
conda-package-handli | 260 KB    | ##################################### | 100%
certifi-2019.6.16    | 156 KB    | ##################################### | 100%
libxml2-2.9.9        | 2.0 MB    | ##################################### | 100%
ca-certificates-2019 | 134 KB    | ##################################### | 100%
chardet-3.0.4        | 173 KB    | ##################################### | 100%
python-3.7.4         | 36.5 MB   | ##################################### | 100%
pysocks-1.7.0        | 29 KB     | ##################################### | 100%
python-libarchive-c- | 23 KB     | ##################################### | 100%
pip-19.2.2           | 1.9 MB    | ##################################### | 100%
conda-4.7.11         | 3.0 MB    | ##################################### | 100%
ncurses-6.1          | 958 KB    | ##################################### | 100%
pycparser-2.19       | 172 KB    | ##################################### | 100%
pyopenssl-19.0.0     | 82 KB     | ##################################### | 100%
idna-2.8             | 101 KB    | ##################################### | 100%
zlib-1.2.11          | 120 KB    | ##################################### | 100%
libedit-3.1.20181209 | 188 KB    | ##################################### | 100%
sqlite-3.29.0        | 1.9 MB    | ##################################### | 100%
zstd-1.3.7           | 887 KB    | ##################################### | 100%
openssl-1.1.1c       | 3.8 MB    | ##################################### | 100%
cryptography-2.7     | 608 KB    | ##################################### | 100%
urllib3-1.24.2       | 153 KB    | ##################################### | 100%
lz4-c-1.8.1.2        | 158 KB    | ##################################### | 100%
setuptools-41.0.1    | 648 KB    | ##################################### | 100%
six-1.12.0           | 22 KB     | ##################################### | 100%
wheel-0.33.4         | 39 KB     | ##################################### | 100%
cffi-1.12.3          | 222 KB    | ##################################### | 100%
tqdm-4.32.1          | 48 KB     | ##################################### | 100%
libarchive-3.3.3     | 1.5 MB    | ##################################### | 100%
bzip2-1.0.8          | 105 KB    | ##################################### | 100%
requests-2.22.0      | 89 KB     | ##################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

In [5]:
%pip install requests
import requests
wikipedia_link='https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M'
raw_wikipedia_page= requests.get(wikipedia_link).text
from bs4 import BeautifulSoup
soup = BeautifulSoup(raw_wikipedia_page,'html')

Requirement already satisfied: requests in /home/jupyterlab/conda/envs/python/lib/python3.6/site-packages (2.22.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /home/jupyterlab/conda/envs/python/lib/python3.6/site-packages (from requests) (1.24.3)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/jupyterlab/conda/envs/python/lib/python3.6/site-packages (from requests) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in /home/jupyterlab/conda/envs/python/lib/python3.6/site-packages (from requests) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in /home/jupyterlab/conda/envs/python/lib/python3.6/site-packages (from requests) (2019.6.16)
Note: you may need to restart the kernel to use updated packages.

In [6]:
My_table = soup.find('table', {"class": 'wikitable sortable'})

In [7]:
New_Table = soup.find('table')

Postcode      = []
Borough       = []
Neighbourhood = []

# Extracting a clean form of the table
for tr_cell in New_Table.find_all('tr'):
    
    counter = 1
    Postcode_var      = -1
    Borough_var       = -1
    Neighbourhood_var = -1
    
    for td_cell in tr_cell.find_all('td'):
        if counter == 1: 
            Postcode_var = td_cell.text
        if counter == 2: 
            Borough_var = td_cell.text
            tag_a_Borough = td_cell.find('a')
        if counter == 3: 
            Neighbourhood_var = str(td_cell.text).strip()
            tag_a_Neighbourhood = td_cell.find('a')
            
        counter +=1
        
    if (Postcode_var == 'Not assigned' or Borough_var == 'Not assigned' or Neighbourhood_var == 'Not assigned'): 
        continue
    try:
        if ((tag_a_Borough is None) or (tag_a_Neighbourhood is None)):
            continue
    except:
        pass
    if(Postcode_var == -1 or Borough_var == -1 or Neighbourhood_var == -1):
        continue
        
    Postcode.append(Postcode_var)
    Borough.append(Borough_var)
    Neighbourhood.append(Neighbourhood_var)

In [8]:
Unique_Postal = set(Postcode)
print('num of unique Postal codes:', len(Unique_Postal))
Postcode_u      = []
Borough_u       = []
Neighbourhood_u = []

for postcode_unique_element in Unique_Postal:
    p_var = ''; b_var = ''; n_var = ''; 
    for postcode_idx, postcode_element in enumerate(Postcode):
        if postcode_unique_element == postcode_element:
            p_var = postcode_element;
            b_var = Borough[postcode_idx]
            if n_var == '': 
                n_var = Neighbourhood[postcode_idx]
            else:
                n_var = n_var + ', ' + Neighbourhood[postcode_idx]
    Postcode_u.append(p_var)
    Borough_u.append(b_var)
    Neighbourhood_u.append(n_var)

num of unique Postal codes: 77

In [9]:
Toronto_Dictionary = {'Postcode':Postcode_u, 'Borough':Borough_u, 'Neighbourhood':Neighbourhood_u}
df_Toronto = pd.DataFrame.from_dict(Toronto_Dictionary)
df_Toronto.to_csv('Toronto_Part-A.csv')
df_Toronto.head(14)

,Postcode,Borough,Neighbourhood
0,M9A,Etobicoke,Islington Avenue
1,M4H,East York,Thorncliffe Park
2,M1B,Scarborough,"Rouge, Malvern"
3,M9L,North York,Humber Summit
4,M4Y,Downtown Toronto,Church and Wellesley
5,M9N,York,Weston
6,M3J,North York,"Northwood Park, York University"
7,M2H,North York,Hillcrest Village
8,M2J,North York,Henry Farm
9,M5S,Downtown Toronto,University of Toronto
10,M1T,Scarborough,Tam O'Shanter
11,M6L,North York,Downsview
12,M8Y,Etobicoke,"Humber Bay, Mimico NE, Old Mill South, The Que..."
13,M3H,North York,"Bathurst Manor, Wilson Heights"

In [21]:
%pip install geocoder

Requirement already satisfied: geocoder in /home/jupyterlab/conda/envs/python/lib/python3.6/site-packages (1.38.1)
Requirement already satisfied: ratelim in /home/jupyterlab/conda/envs/python/lib/python3.6/site-packages (from geocoder) (0.1.6)
Requirement already satisfied: requests in /home/jupyterlab/conda/envs/python/lib/python3.6/site-packages (from geocoder) (2.22.0)
Requirement already satisfied: future in /home/jupyterlab/conda/envs/python/lib/python3.6/site-packages (from geocoder) (0.17.1)
Requirement already satisfied: six in /home/jupyterlab/conda/envs/python/lib/python3.6/site-packages (from geocoder) (1.12.0)
Requirement already satisfied: click in /home/jupyterlab/conda/envs/python/lib/python3.6/site-packages (from geocoder) (7.0)
Requirement already satisfied: decorator in /home/jupyterlab/conda/envs/python/lib/python3.6/site-packages (from ratelim->geocoder) (4.4.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /home/jupyterlab/conda/envs/python/lib/python3.6/site-packages (from requests->geocoder) (1.24.3)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/jupyterlab/conda/envs/python/lib/python3.6/site-packages (from requests->geocoder) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in /home/jupyterlab/conda/envs/python/lib/python3.6/site-packages (from requests->geocoder) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in /home/jupyterlab/conda/envs/python/lib/python3.6/site-packages (from requests->geocoder) (2019.6.16)
Note: you may need to restart the kernel to use updated packages.

In [11]:
import geocoder

In [12]:
Table_PostalCode = soup.find('table')
fields = Table_PostalCode.find_all('td')

postcode = []
borough = []
neighbourhood = []

for i in range(0, len(fields), 3):
    postcode.append(fields[i].text.strip())
    borough.append(fields[i+1].text.strip())
    neighbourhood.append(fields[i+2].text.strip())
        
df_PostalCode = pd.DataFrame(data=[postcode, borough, neighbourhood]).transpose()
df_PostalCode.columns = ['Postcode', 'Borough', 'Neighbourhood']
df_PostalCode.head()

  Postcode           Borough     Neighbourhood
0      M1A      Not assigned      Not assigned
1      M2A      Not assigned      Not assigned
2      M3A        North York         Parkwoods
3      M4A        North York  Victoria Village
4      M5A  Downtown Toronto      Harbourfront

In [13]:

df_PostalCode['Borough'].replace('Not assigned', np.nan, inplace=True)
df_PostalCode.dropna(subset=['Borough'], inplace=True)

df_PostalCode.head()

  Postcode           Borough     Neighbourhood
2      M3A        North York         Parkwoods
3      M4A        North York  Victoria Village
4      M5A  Downtown Toronto      Harbourfront
5      M5A  Downtown Toronto       Regent Park
6      M6A        North York  Lawrence Heights

In [14]:
df_PostalCodeNeighbor = df_PostalCode.groupby(['Postcode', 'Borough'])['Neighbourhood'].apply(', '.join).reset_index()
df_PostalCodeNeighbor.columns = ['Postcode', 'Borough', 'Neighbourhood']
df_PostalCodeNeighbor

    Postcode      Borough                                      Neighbourhood
0        M1B  Scarborough                                     Rouge, Malvern
1        M1C  Scarborough             Highland Creek, Rouge Hill, Port Union
2        M1E  Scarborough                  Guildwood, Morningside, West Hill
3        M1G  Scarborough                                             Woburn
4        M1H  Scarborough                                          Cedarbrae
..       ...          ...                                                ...
98       M9N         York                                             Weston
99       M9P    Etobicoke                                          Westmount
100      M9R    Etobicoke  Kingsview Village, Martin Grove Gardens, Richv...
101      M9V    Etobicoke  Albion Gardens, Beaumond Heights, Humbergate, ...
102      M9W    Etobicoke                                          Northwest

[103 rows x 3 columns]

In [15]:
df_PostalCodeNeighbor['Neighbourhood'].replace('Not assigned', "Queen's Park", inplace=True)
df_PostalCodeNeighbor

    Postcode      Borough                                      Neighbourhood
0        M1B  Scarborough                                     Rouge, Malvern
1        M1C  Scarborough             Highland Creek, Rouge Hill, Port Union
2        M1E  Scarborough                  Guildwood, Morningside, West Hill
3        M1G  Scarborough                                             Woburn
4        M1H  Scarborough                                          Cedarbrae
..       ...          ...                                                ...
98       M9N         York                                             Weston
99       M9P    Etobicoke                                          Westmount
100      M9R    Etobicoke  Kingsview Village, Martin Grove Gardens, Richv...
101      M9V    Etobicoke  Albion Gardens, Beaumond Heights, Humbergate, ...
102      M9W    Etobicoke                                          Northwest

[103 rows x 3 columns]

In [16]:
df_PostalCodeNeighbor.shape

(103, 3)

In [17]:

df_geospatial_data = pd.read_csv('http://cocl.us/Geospatial_data')
df_geospatial_data.columns = ['Postcode', 'Latitude', 'Longitude']
df_geospatial_data.head()

  Postcode   Latitude  Longitude
0      M1B  43.806686 -79.194353
1      M1C  43.784535 -79.160497
2      M1E  43.763573 -79.188711
3      M1G  43.770992 -79.216917
4      M1H  43.773136 -79.239476

In [18]:
df_Post = pd.merge(df_PostalCodeNeighbor, df_geospatial_data, on=['Postcode'], how='inner')
df_Full_Table = df_Post[[ 'Postcode', 'Borough', 'Neighbourhood', 'Latitude', 'Longitude',]].copy()
df_Full_Table.head()

,Postcode,Borough,Neighbourhood,Latitude,Longitude
0,M1B,Scarborough,"Rouge, Malvern",43.806686,-79.194353
1,M1C,Scarborough,"Highland Creek, Rouge Hill, Port Union",43.784535,-79.160497
2,M1E,Scarborough,"Guildwood, Morningside, West Hill",43.763573,-79.188711
3,M1G,Scarborough,Woburn,43.770992,-79.216917
4,M1H,Scarborough,Cedarbrae,43.773136,-79.239476

In [19]:
df_Full_Table.head(103)

,Postcode,Borough,Neighbourhood,Latitude,Longitude
0,M1B,Scarborough,"Rouge, Malvern",43.806686,-79.194353
1,M1C,Scarborough,"Highland Creek, Rouge Hill, Port Union",43.784535,-79.160497
2,M1E,Scarborough,"Guildwood, Morningside, West Hill",43.763573,-79.188711
3,M1G,Scarborough,Woburn,43.770992,-79.216917
4,M1H,Scarborough,Cedarbrae,43.773136,-79.239476
...,...,...,...,...,...
98,M9N,York,Weston,43.706876,-79.518188
99,M9P,Etobicoke,Westmount,43.696319,-79.532242
100,M9R,Etobicoke,"Kingsview Village, Martin Grove Gardens, Richv...",43.688905,-79.554724
101,M9V,Etobicoke,"Albion Gardens, Beaumond Heights, Humbergate, ...",43.739416,-79.588437
102,M9W,Etobicoke,Northwest,43.706748,-79.594054